version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            npm install
      - save_cache:
        paths:
          - node_modules
          - ~/.npm
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
